[versions]
# renovate: packageName=eza-community/eza
eza = "0.19.0"
# renovate: datasource=github-tags packageName=golang/go extractVersion="(?<version>go\\d+(\\.\\d+)+)"
golang = "1.22"
# renovate: packageName=BurntSushi/ripgrep
ripgrep = "14.1.1"
