# -*- mode: ini -*-

{{ if not (or .headless .ephemeral) }}
[".tmux/plugins/nord-tmux"]
    type = "archive"
    url = "https://github.com/arcticicestudio/nord-tmux/archive/refs/heads/develop.zip"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
{{ end }}

# ripgrep
{{ $rgarch := ""}}
{{ if and (eq .chezmoi.os "darwin") (eq .chezmoi.arch "arm64") }}
    {{ $rgarch = "aarch64-apple-darwin" }}
{{ else if (eq .chezmoi.arch "amd64") -}}
    {{ $rgarch = "x86_64-unknown-linux-musl" }}
{{ else if (or .raspi (eq .chezmoi.arch "arm")) -}}
    {{ $rgarch = "armv7-unknown-linux-gnueabihf" }}
{{ else }}
    {{ $rgarch = "x86_64-unknown-linux-musl" }}
{{ end -}}
["bin/rg"]
type = "archive-file"
url = "https://github.com/BurntSushi/ripgrep/releases/download/{{ .versions.ripgrep }}/ripgrep-{{ .versions.ripgrep }}-{{ $rgarch }}.tar.gz"
path = "ripgrep-{{ .versions.ripgrep }}-{{ $rgarch }}/rg"

# delta
{{ if eq .chezmoi.os "linux" }}
{{ $deltaarch := ""}}
{{ if (eq .chezmoi.arch "amd64") -}}
    {{ $deltaarch = "x86_64-unknown-linux-musl" }}
{{ else if (or .raspi (eq .chezmoi.arch "arm")) -}}
    {{ $deltaarch = "arm-unknown-linux-gnueabihf" }}
{{ else }}
    {{ $deltaarch = "x86_64-unknown-linux-musl" }}
{{ end -}}
["bin/delta"]
type = "archive-file"
url = "https://github.com/dandavison/delta/releases/download/{{ .versions.delta }}/delta-{{ .versions.delta }}-{{ $deltaarch }}.tar.gz"
path = "delta-{{ .versions.delta }}-{{ $deltaarch }}/delta"
{{ end }}

{{ if and (eq .chezmoi.os "linux") (eq .chezmoi.arch "amd64") }}
# renovate: datasource=github-tags packageName=kubernetes/kubernetes
["bin/kubectl"]
    type = "file"
    url = "https://dl.k8s.io/release/v1.29.6/bin/linux/amd64/kubectl"
    executable = true
{{ end }}

{{ if and (eq .chezmoi.os "linux") (eq .chezmoi.arch "amd64") }}
["bin/direnv"]
    type = "file"
    url = "https://github.com/direnv/direnv/releases/download/v2.35.0/direnv.linux-amd64"
    executable = true
{{end}}
