[versions]
# renovate: packageName=eza-community/eza
eza = "0.23.2"
# renovate: datasource=github-tags packageName=golang/go extractVersion="(?<version>go\\d+(\\.\\d+)+)"
golang = "1.22"
# renovate: packageName=BurntSushi/ripgrep
ripgrep = "14.1.1"
# renovate: datasource=github-tags packageName=zsh-users/zsh-autosuggestions
zshautosuggestions = "0.7.1"
