[versions]
# renovate: packageName=eza-community/eza
eza = "0.23.4"
# renovate: datasource=github-tags packageName=golang/go extractVersion="(?<version>go\\d+(\\.\\d+)+)"
golang = "1.22"
# renovate: packageName=BurntSushi/ripgrep
ripgrep = "15.1.0"
# renovate: datasource=github-tags packageName=zsh-users/zsh-autosuggestions
zshautosuggestions = "0.7.1"
