# -*- mode: ini -*-

{{ $ezaarch := ""}}
{{ if eq .chezmoi.arch "amd64" -}}
{{ $ezaarch = "x86_64-unknown-linux-gnu" }}
{{ else if eq .chezmoi.arch "arm64" -}}
    {{ $ezaarch = "aarch64-unknown-linux-gnu" }}
{{ else if .raspi -}}
    {{ $ezaarch = "arm-unknown-linux-gnueabihf" }}
{{ end -}}
["bin/eza"]
type = "archive-file"
url = "https://github.com/eza-community/eza/releases/download/v{{ .versions.eza }}/eza_{{ $ezaarch }}.tar.gz"
path = "./eza"
