# -*- mode: ini -*-

["bin/PrusaSlicer"]
    type = "file"
    {{- $assetPattern := "PrusaSlicer-*+linux-x64-older-distros-GTK3-*.AppImage" }}
    url = {{ gitHubReleaseAssetURL "prusa3d/PrusaSlicer" "version_2.8.1" $assetPattern | quote }}
    executable = true

[".local/share/icons/PrusaSlicer.svg"]
    type = "file"
    url = "https://raw.githubusercontent.com/prusa3d/PrusaSlicer/master/resources/icons/PrusaSlicer.svg"
